### ISSUE TITLE
How do you grab and categorize plugins?

### ISSUE THREAD

**Issue by edgarsgriga** [HighwayofLife/awesome-chatgpt-plugins#35]
Hello,

I'm new to this, and I'm fascinated by the power of GitHub.

1. I'm wondering how you obtain those plugins from the ChatGPT plugin store. Is it done through scraping?

2. How are they categorized? Is it done manually or automatically?

3. Are all the plugins currently available in the plugin store, or are some of them added to this list outside of ChatGPT? How can I determine which ones are already available in the store?

I appreciate your time and effort!

**Comment by HighwayofLife** [comment]
Hi @heyitsmedev, thanks for your question. 

1. There's a URL to obtain the plugin list. `https://chat.openai.com/backend-api/aip/p?statuses=approved&offset=0&limit=0` This is a large file at this point. You need to use your Auth-bearer token to obtain the contents of this file, which also means you must be a ChatGPT plus subscriber to grab it. I use a cURL call to download the file. I haven't been able to automate this part of the process as the OpenAI site firewall actively blocks automation.

2. There is a notebook you can go through to see the exact process, it's entirely automated. But here's the process in a nutshell. First, we grab all of the plugins and for each plugin, take the plugin name, plugin description (the portion shown to the human), and the plugin description that is available to the ChatGPT model being used, which is a far more verbose description, I then send this information to the ChatGPT 3.5-turbo model to generate a new description for the human and attempt to have ChatGPT assign the plugin a category from the pre-defined category list. I then take this information and plug it through a categorization process that uses keywords from the plugin name, description, and enhanced descriptions. Using weights, score the number of times those words appear in each location. Then we choose the highest weighted category from the scoring and that's the category the plugin is placed into. It's not always 100% the most accurate and a ton of plugins could in theory be placed into several categories, so this is a way to make a "best guess". 

3. Yes, these are all of the plugins currently available in the ChatGPT plugin store. None are currently added outside of the plugin store. Every plugin you see here is in the store unless it has recently been removed. Every update there is always one or more plugin being removed, so that can happen. But there are about 1000 plugins currently available.
